# Generated by Django 4.2.19 on 2025-02-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'StateList'},
        ),
    ]
